{{- if and (.Values.ingress.enabled) (eq .Values.ingress.class "contour") -}}
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: {{ template "foundry-vtt.fullname" . }}
  labels:
    app: {{ template "foundry-vtt.fullname" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  annotations:
# {{- if .Values.ingress.configurationSnippet }}
#     nginx.ingress.kubernetes.io/configuration-snippet: |
#       {{- template "configurationSnippet" . }}
# {{- end }}
# {{- if eq .Values.tls "external" }}
#     nginx.ingress.kubernetes.io/ssl-redirect: "false" # turn off ssl redirect for external.
# {{- else }}
#   {{- if ne .Values.ingress.tls.source "secret" }}
#     {{- $certmanagerVer :=  split "." .Values.certmanager.version -}}
#     {{- if or (.Capabilities.APIVersions.Has "cert-manager.io/v1alpha2") (and (eq (int $certmanagerVer._0) 0) (ge (int $certmanagerVer._1) 11)) }}
#     cert-manager.io/issuer: {{ template "foundry-vtt.fullname" . }}
#     cert-manager.io/issuer-kind: Issuer
#     {{- else if or (.Capabilities.APIVersions.Has "certmanager.k8s.io/v1alpha1") (and (eq (int $certmanagerVer._0) 0) (lt (int $certmanagerVer._1) 11)) }}
#     certmanager.k8s.io/issuer: {{ template "foundry-vtt.fullname" . }}
#     {{- end }}
#   {{- end }}
# {{- end }}
{{- if .Values.ingress.extraAnnotations }}
{{ toYaml .Values.ingress.extraAnnotations | indent 4 }}
{{- end }}
spec:
  virtualhost:
    fqdn: {{ .Values.ingress.hostname }}
    {{- if eq .Values.tls "ingress" }}
    tls:
      {{- if eq .Values.ingress.tls.source "secret" }}
      secretName: {{ template "foundry-vtt.fullname" . }}-signed
      {{- else }}
      secretName: {{ template "foundry-vtt.fullname" . }}-ingress
      {{- end}}
    {{- end }}
  routes:
    - conditions:
      - prefix: /
      services:
        - name: {{ template "foundry-vtt.fullname" . }}
          port: 80
    - conditions:
      - prefix: /socket.io
      enableWebsockets: true  # Setting this to true enables websocket for all paths that match /websocket
      services:
        - name: {{ template "foundry-vtt.fullname" . }}
          port: 80
{{- end }}